shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 5.0

planner_frequency: 0.001
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.5

# Local planner
base_local_planner: dwa_local_planner/DWAPlannerROS

# Global planner
base_global_planner: custom_astar/CustomAStarExpansion
