
# Global planner parameters
GlobalPlanner:
  heuristic_type: "manhattan"   # Options: "euclidean", "manhattan"
  use_dijkstra: false           # Enable A*
  allow_unknown: true           # Allow unknown cells
  default_tolerance: 0.5        # Acceptable distance from goal
  use_quadratic: true           # Smoother paths
  use_grid_path: false          # Gradient-based paths
  planner_window_x: 0.0         # Local search window width
  planner_window_y: 0.0         # Local search window height
  publish_scale: 100            # Scale for potential field visualization
  outline_map: true             # Disable map outline
  old_navfn_behavior: false     # Use modern behavior
  neutral_cost: 50              # Cost for free space
  lethal_cost: 253              # Cost for obstacles
  cost_factor: 3.0              # Scaling for costs
  orientation_filter: true      # Smooth final orientation